version: "3"
services:
    app:
        build: ./nodejs
        container_name: nodejs
        ports:
            - '3000:3000'

    php:
        image: php:7.4.27-fpm
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./php:/php
